# SPDX-License-Identifier: MPL-2.0
name: varkiel-agent
language: python
package_manager: pip
runtime:
  python: "3.11.7"
  node: "20.12.2"
entrypoints:
  web:
    command: scripts/dev
    description: Flask development server with hot reload
  cli:
    module: varkiel.main
    description: Interactive command-line interface for experimentation
ports:
  - 8000
service_type: web-service
owners:
  - Lexsight LLC <contact@lexsight.ai>
